name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: moon version
        run: |
          moon version --all
          moonrun --version

      - name: moon update
        run: moon update

      - name: moon build
        run: |
          moon build --target all
      
      - name: moon build --target native
        run: |
          moon build --target native
      
      - name: moon test
        run: |
          moon test --target all

      - name: moon test --target native
        run: |
          moon test --target native
      
      